### ISSUE TITLE
It crashes on startup (noob here)

### ISSUE THREAD

**Issue by Ezzocorbi** [UnderMybrella/EternalJukebox#70]
### Before
- [x] I have checked for similar issues already
- [x] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
It crashes as soon as I start it if I put the config file in the folder.

### Console Logs
https://pastebin.com/P2zZpiXy

### Song
None

### Additional Information
I'm a noob at this, my guess is that I have done something wrong in the config, here's my config file (without the Spotify and Youtube keys) https://pastebin.com/5exMRjEh

Also where does the config.yaml go? I put it in "Desktop\The Etenal Jukebox\web", is that the right folder?

I'm on Windows 10 using Java 8 221

**Comment by Ezzocorbi** [comment]
I got it working by deleting this part of the config file:
```
# Can either be JDBC or H2
# If H2, you'll need to provide 'databaseName' under options, or leave it blank to default to 'eternal_jukebox'
# The values below are only needed if you're connecting to something like a MySQL database
databaseType: JDBC
databaseOptions:
  username: <sql_username>
  password: <sql_password>
  jdbcUrl: jdbc:<sql_type>://<sql_host>:<sql_port>/<sql_database_name>?useSSL=false
```
